Fix ClassLoader missing_method issue in SignatureTest for Android B
The addition of the ANR warning listener uses a lambda which generated a
synthetic private method inside the ProfilingManager class. Because the
synthetic method takes `AnrWarningResult` as a parameter (a class only
present in Android C+), any reflective call to `getDeclaredMethods()`
on Android B results in a `NoClassDefFoundError`.

This causes `CtsCurrentApiSignatureTestCases` to fail with
`missing_method` for all `ProfilingManager` methods as the CTS test
suppresses this exception and treats it as all methods missing.

This CL extracts the listener creation into a nested factory class
that will only be loaded if the listener is required, avoiding the
classloader linkage error when inspecting the `ProfilingManager` class.

Test: m framework-profiling
Bug: 498844433
Flag: EXEMPT BUGFIX
Cherrypick-From: https://googleplex-android-review.googlesource.com/q/commit:a03f1baf7206d95208e76f5b9c5419930415b808
Merged-In: I84084b63237a0014a928eaed1ef78d42b33bd59a
Change-Id: I84084b63237a0014a928eaed1ef78d42b33bd59a